# TODO add description of the config file
worker_threads: 2

whitelists:
  - 192.168.0.0/16
  - 10.0.0.0/8

presets:
  ip: (?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)
  date_time: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d+

sources:
  - type: journal
    unit: sshd
    rules:
      - name: ssh
        ban_duration: 1h
        window: 1h
        max_attempts: 5
        ban_action: nftables-allports
        pattern:
          - Failed password for (.*) from
          - (?P<ip>[^ ]+)
  - type: file
    path: /tmp/jupyter.log
    rules:
      - name: jupyter
        ban_duration: 2h
        window: 1h
        max_attempts: 5
        ban_action: nftables-allports
        pattern:
          - Failed password for (.*) from
          - (?P<ip>[^ ]+)
