# TODO add description of the config file
worker_threads: 2

whitelists:
  - 192.168.0.0/16
  - 10.0.0.0/8

presets:
  ip: (?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)
  date_time: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d+

actions:
  nftables-allports:
    init: |-
      # Exit early if the table already exists
      nft list table inet logban &>/dev/null && exit 0;
      
      # Create the table and the set
      nft add table inet logban;
      nft add set inet logban banned_ipv4 '{ type ipv4_addr; flags timeout; }';
      
      # Create the INPUT chain and attach the filter hook
      nft add chain inet logban INPUT '{ type filter hook input priority 0; policy accept; }';
      
      # Add rules to block IPv4 and IPv6 addresses
      nft add rule inet logban INPUT ip  saddr @banned_ipv4 drop;
    ban: nft add element inet logban banned_ipv4 { $ip timeout ${timeout_sec}s };
    # unban: nft delete element inet logban banned_ipv4 { $ip };

sources:
  - type: journal
    unit: sshd
    rules:
      - name: ssh
        ban_duration: 1h
        window: 1h
        max_attempts: 5
        ban_action: nftables-allports
        pattern:
          - Failed password for (.*) from
          - (?P<ip>[^ ]+)
  - type: file
    path: /tmp/jupyter.log
    rules:
      - name: jupyter
        ban_duration: 5m
        window: 10s
        max_attempts: 2
        ban_action: nftables-allports
        pattern:
          - Failed password for (.*) from
          - (?P<ip>[^ ]+)
